### ISSUE TITLE
How does it work without gadgets

### ISSUE THREAD

**Issue by arjun-g** [alexa/skill-sample-nodejs-buttons-trivia#1]
Hi,

How does this work without a echo buttons ? If I want to build a skill which automatically adapts for both with buttons or without buttons cases is this the right thing to start or should  I start from scratch ?

**Comment by mdinescu** [comment]
You can either start by modifying this template, or just use the template as a reference and implement your own skill from scratch.

When making a trivia-style game that works without buttons you have to come up with a solution for the "buzz in" mechanism if you'd like to support multiple players: this is the part where, after Alexa asks a question, one of the players gives the answer. With buttons, the player that gives the answer is the one who pressed a button. Without, you might have to have Alexa ask after each question: "which player knows the answer?" and wait for the players to say "player 2" or their name before giving the answer to the question. If you'd like to allow for both "with-buttons" and "no-buttons" modes in multi-player, you'll also have to introduce a configuration state where Alexa will have a conversation with the players to decide if the game will be played with or without buttons.

Probably the simplest way to provide no-button support for a trivia game is to only allow single player mode without buttons. That way, the flow is such that Alexa simply asks the question and then immediately waits for an answer since there are no other players involved. 

In either case, after you've decided on what the game play looks like without buttons, you can modify the template to work that way.

**Comment by arjun-g** [comment]
Thank You Mike. I will look into how to modify this template for my case. I have one more doubt,

1, I am planning to ask the user a one time question whether they would use the button or not.

2, In one of my published trivia skill I have implemented a multi player mode where Alexa will ask the questions one by one for each participating player in rotation.

Are these two a good user experience or should I need to find some other way to go about it ?

**Comment by mdinescu** [comment]
S​o each player would get different questions? I suppose that could be fine.
It's just quite a bit different than the experience playing with buttons
where you compete for the answer to the same question.

Regarding the one-time question, yes, I think so. I'm assuming by one time
you mean you ask once each time the game starts​.

**Comment by arjun-g** [comment]
Yes each player would get a different question.

Regarding the one-time question I meant only once when the user launches the app for the first time.

**Comment by hawaiidude** [comment]
Keep getting Error in Cloudwatch
Tried folders in ROOT
Tried folders in CUSTOM
Tried folders in LAMBDA/CUSTOM
Keep getting same Error...

Any suggestions?

Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/index.js:5:23)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by mdinescu** [comment]
How did you deploy the skill? did you use the ASK CLI?  Or did you do a manual deployment?

**Comment by mdinescu** [comment]
Closing this issue.
