### ISSUE TITLE
In App Purchase

### ISSUE THREAD

**Issue by CraigHDev** [alexa/skill-sample-nodejs-buttons-trivia#12]
Hi,

I have been playing around with the skill and was wondering how to add in app purchases for more questions to this skill? I would also like to add hints as possible purchase also.

Do you have any tutorials for this? only tutorial i could find was for the fact skill and not sure how to reconfigure it to work on this skill.

Any help would be appreciated : )

**Comment by franklin-lobb** [comment]
check out the [name the show sample](https://github.com/alexa/skill-sample-nodejs-name-the-show).  It uses a consumable ISP for hints.

There's a [workshop version](https://github.com/alexa/workshop-in-skill-purchasing) that takes you through adding ISP to name the show, which can help guide you through the process.

**Comment by CraigHDev** [comment]
Thanks, just had a look and this seems very helpful.

Is there a workshop available for adding items like additional  question packs? Bit of a rookie with this stuff so any help would be appreciated.

**Comment by mdinescu** [comment]
Craig - we don't have any workshops that are specifically built around modifying the trivia sample skill but using the examples that Franklin recommended, I would try the following: 
- first, onboard with ISP (in skill purchases) for your skill 
- then start making some modifications to the trivia skill in the area that handles answers and scoring, and instead of giving up after the user gives the incorrect answer several times, prompt them if they would like a hint
- you'll probably have to define a mapping between questions and hints and if a hint is needed, and enabled, render the hint
